import { existsSync, readFileSync } from 'fs';
import { basename, join, resolve } from 'path';
import { t } from '../core/messages.ts';

interface BrandRoot {
  path: string;
  brand: string;
}

function readBrandFromAgents(dir: string): string | null {
  const agentsMd = join(dir, 'AGENTS.md');
  if (!existsSync(agentsMd)) return null;
  try {
    const content = readFileSync(agentsMd, 'utf8');
    // Match the title generated by `kbrain setup`: "# <Brand> — AGENTS.md"
    const m = content.match(/^#\s+(\S[^\n—]*?)\s+—\s+AGENTS\.md/m);
    return m ? m[1].trim() : null;
  } catch {
    return null;
  }
}

function findBrandRoot(startDir: string): BrandRoot | null {
  let cur = resolve(startDir);
  while (true) {
    if (existsSync(join(cur, '.kbrain-overseer', 'config.json'))) {
      const brand = readBrandFromAgents(cur) ?? basename(cur);
      return { path: cur, brand };
    }
    if (existsSync(join(cur, '.claude', 'agents', 'context-router.md')) && existsSync(join(cur, 'AGENTS.md'))) {
      const brand = readBrandFromAgents(cur);
      if (brand) return { path: cur, brand };
    }
    const parent = resolve(cur, '..');
    if (parent === cur) return null;
    cur = parent;
  }
}

export async function runNew(args: string[]) {
  const positional = args.filter(a => !a.startsWith('--'));
  const name = positional[0];
  if (!name) {
    console.error(t('new.usage'));
    process.exit(1);
  }

  const found = findBrandRoot(process.cwd());
  if (!found) {
    console.error(t('new.error.not_brand_root', { cwd: process.cwd() }));
    process.exit(1);
  }

  const roomPath = join(found.path, 'room', name);
  const passThrough: string[] = [
    '--path', roomPath,
    '--name', name,
    '--parent-brand', found.brand,
    '--non-interactive',
  ];
  if (args.includes('--force')) passThrough.push('--force');
  if (args.includes('--json')) passThrough.push('--json');

  const { runInitRoom } = await import('./init-room.ts');
  await runInitRoom(passThrough);

  // Auto-refresh Overseer registry if one exists for this brand root.
  const overseerCfg = join(found.path, '.kbrain-overseer', 'config.json');
  if (existsSync(overseerCfg)) {
    const { runInitOverseer } = await import('./init-overseer.ts');
    await runInitOverseer(['--root', found.path, '--force']);
  }
}
